// Auto-generated by running `pnpm generate:dts-exports`
import type {ConcurrencyLimiter} from '@sanity/util/concurrency-limiter'
import {describe, expectTypeOf, test} from 'vitest'

describe('@sanity/util/concurrency-limiter', () => {
  test('ConcurrencyLimiter', () => {
    expectTypeOf<ConcurrencyLimiter>().not.toBeNever()
  })
})
