// Auto-generated by running `pnpm generate:dts-exports`
import type {
  fromString,
  get,
  hasFocus,
  hasItemFocus,
  isEqual,
  isExpanded,
  isSegmentEqual,
  numEqualSegments,
  pathFor,
  resolveKeyedPath,
  _resolveKeyedPath,
  startsWith,
  trimChildPath,
  trimLeft,
  trimRight,
  FOCUS_TERMINATOR,
  toString,
} from '@sanity/util/paths'
import {describe, expectTypeOf, test} from 'vitest'

describe('@sanity/util/paths', () => {
  test('fromString', () => {
    expectTypeOf<typeof fromString>().toBeFunction()
  })
  test('get', () => {
    expectTypeOf<typeof get>().toBeFunction()
  })
  test('get', () => {
    expectTypeOf<typeof get>().toBeFunction()
  })
  test('hasFocus', () => {
    expectTypeOf<typeof hasFocus>().toBeFunction()
  })
  test('hasItemFocus', () => {
    expectTypeOf<typeof hasItemFocus>().toBeFunction()
  })
  test('isEqual', () => {
    expectTypeOf<typeof isEqual>().toBeFunction()
  })
  test('isExpanded', () => {
    expectTypeOf<typeof isExpanded>().toBeFunction()
  })
  test('isSegmentEqual', () => {
    expectTypeOf<typeof isSegmentEqual>().toBeFunction()
  })
  test('numEqualSegments', () => {
    expectTypeOf<typeof numEqualSegments>().toBeFunction()
  })
  test('pathFor', () => {
    expectTypeOf<typeof pathFor>().toBeFunction()
  })
  test('resolveKeyedPath', () => {
    expectTypeOf<typeof resolveKeyedPath>().toBeFunction()
  })
  test('_resolveKeyedPath', () => {
    expectTypeOf<typeof _resolveKeyedPath>().toBeFunction()
  })
  test('startsWith', () => {
    expectTypeOf<typeof startsWith>().toBeFunction()
  })
  test('trimChildPath', () => {
    expectTypeOf<typeof trimChildPath>().toBeFunction()
  })
  test('trimLeft', () => {
    expectTypeOf<typeof trimLeft>().toBeFunction()
  })
  test('trimRight', () => {
    expectTypeOf<typeof trimRight>().toBeFunction()
  })
  test('FOCUS_TERMINATOR', () => {
    expectTypeOf<typeof FOCUS_TERMINATOR>().not.toBeNever()
  })
  test('toString', () => {
    expectTypeOf<typeof toString>().toBeFunction()
  })
})
