// Auto-generated by running `pnpm generate:dts-exports`
import type {createClientConcurrencyLimiter} from '@sanity/util/client'
import {describe, expectTypeOf, test} from 'vitest'

describe('@sanity/util/client', () => {
  test('createClientConcurrencyLimiter', () => {
    expectTypeOf<typeof createClientConcurrencyLimiter>().toBeFunction()
  })
})
