// Auto-generated by running `pnpm generate:dts-exports`
import type {
  findQueriesInPath,
  findQueriesInSource,
  getResolver,
  readConfig,
  readSchema,
  registerBabel,
  safeParseQuery,
  CodegenConfig,
  TypeGenerator,
} from '@sanity/codegen'
import {describe, expectTypeOf, test} from 'vitest'

describe('@sanity/codegen', () => {
  test('findQueriesInPath', () => {
    expectTypeOf<typeof findQueriesInPath>().toBeFunction()
  })
  test('findQueriesInSource', () => {
    expectTypeOf<typeof findQueriesInSource>().toBeFunction()
  })
  test('getResolver', () => {
    expectTypeOf<typeof getResolver>().toBeFunction()
  })
  test('readConfig', () => {
    expectTypeOf<typeof readConfig>().toBeFunction()
  })
  test('readSchema', () => {
    expectTypeOf<typeof readSchema>().toBeFunction()
  })
  test('registerBabel', () => {
    expectTypeOf<typeof registerBabel>().toBeFunction()
  })
  test('safeParseQuery', () => {
    expectTypeOf<typeof safeParseQuery>().toBeFunction()
  })
  test('CodegenConfig', () => {
    expectTypeOf<CodegenConfig>().not.toBeNever()
  })
  test('TypeGenerator', () => {
    expectTypeOf<TypeGenerator>().not.toBeNever()
  })
})
