// Auto-generated by running `pnpm generate:dts-exports`
import type {
  isDeepEmpty,
  isShallowEmptyObject,
  randomKey,
  resolveTypeName,
  isEmpty,
  isEmptyArray,
  isEmptyObject,
} from '@sanity/util/content'
import {describe, expectTypeOf, test} from 'vitest'

describe('@sanity/util/content', () => {
  test('isDeepEmpty', () => {
    expectTypeOf<typeof isDeepEmpty>().toBeFunction()
  })
  test('isShallowEmptyObject', () => {
    expectTypeOf<typeof isShallowEmptyObject>().toBeFunction()
  })
  test('randomKey', () => {
    expectTypeOf<typeof randomKey>().toBeFunction()
  })
  test('resolveTypeName', () => {
    expectTypeOf<typeof resolveTypeName>().toBeFunction()
  })
  test('isEmpty', () => {
    expectTypeOf<typeof isEmpty>().not.toBeNever()
  })
  test('isEmptyArray', () => {
    expectTypeOf<typeof isEmptyArray>().not.toBeNever()
  })
  test('isEmptyObject', () => {
    expectTypeOf<typeof isEmptyObject>().not.toBeNever()
  })
})
