// Auto-generated by running `pnpm generate:dts-exports`
import type {createSafeJsonParser} from '@sanity/util/createSafeJsonParser'
import {describe, expectTypeOf, test} from 'vitest'

describe('@sanity/util/createSafeJsonParser', () => {
  test('createSafeJsonParser', () => {
    expectTypeOf<typeof createSafeJsonParser>().toBeFunction()
  })
})
