// Auto-generated by running `pnpm generate:dts-exports`
import type {
  format,
  isValidTimeZoneString,
  parse,
  DEFAULT_DATE_FORMAT,
  DEFAULT_TIME_FORMAT,
  ParseResult,
  sanitizeLocale,
} from '@sanity/util/legacyDateFormat'
import {describe, expectTypeOf, test} from 'vitest'

describe('@sanity/util/legacyDateFormat', () => {
  test('format', () => {
    expectTypeOf<typeof format>().toBeFunction()
  })
  test('isValidTimeZoneString', () => {
    expectTypeOf<typeof isValidTimeZoneString>().toBeFunction()
  })
  test('parse', () => {
    expectTypeOf<typeof parse>().toBeFunction()
  })
  test('DEFAULT_DATE_FORMAT', () => {
    expectTypeOf<typeof DEFAULT_DATE_FORMAT>().not.toBeNever()
  })
  test('DEFAULT_TIME_FORMAT', () => {
    expectTypeOf<typeof DEFAULT_TIME_FORMAT>().not.toBeNever()
  })
  test('ParseResult', () => {
    expectTypeOf<ParseResult>().not.toBeNever()
  })
  test('sanitizeLocale', () => {
    expectTypeOf<typeof sanitizeLocale>().not.toBeNever()
  })
})
