// Auto-generated by running `pnpm generate:dts-exports`
import type {absolutify, expandHome, pathIsEmpty} from '@sanity/util/fs'
import {describe, expectTypeOf, test} from 'vitest'

describe('@sanity/util/fs', () => {
  test('absolutify', () => {
    expectTypeOf<typeof absolutify>().toBeFunction()
  })
  test('expandHome', () => {
    expectTypeOf<typeof expandHome>().toBeFunction()
  })
  test('pathIsEmpty', () => {
    expectTypeOf<typeof pathIsEmpty>().toBeFunction()
  })
})
