// Auto-generated by running `pnpm generate:dts-exports`
import type {VisionLocaleResourceKeys, visionTool, VisionToolConfig} from '@sanity/vision'
import {describe, expectTypeOf, test} from 'vitest'

describe('@sanity/vision', () => {
  test('VisionLocaleResourceKeys', () => {
    expectTypeOf<VisionLocaleResourceKeys>().not.toBeNever()
  })
  test('visionTool', () => {
    expectTypeOf<typeof visionTool>().not.toBeNever()
  })
  test('VisionToolConfig', () => {
    expectTypeOf<VisionToolConfig>().toBeObject()
  })
})
