// Auto-generated by running `pnpm generate:dts-exports`
import type {default as _default, Schema, SchemaValidationResult} from '@sanity/schema'
import {describe, expectTypeOf, test} from 'vitest'

describe('@sanity/schema', () => {
  test('default', () => {
    expectTypeOf<_default>().not.toBeNever()
  })
  test('Schema', () => {
    expectTypeOf<typeof Schema>().not.toBeNever()
  })
  test('SchemaValidationResult', () => {
    expectTypeOf<SchemaValidationResult>().toBeObject()
  })
})
