// Auto-generated by running `pnpm generate:dts-exports`
import type {defineQuery, default as _default} from 'groq'
import {describe, expectTypeOf, test} from 'vitest'

describe('groq', () => {
  test('defineQuery', () => {
    expectTypeOf<typeof defineQuery>().toBeFunction()
  })
  test('default', () => {
    expectTypeOf<typeof _default>().toBeFunction()
  })
})
