// Auto-generated by running `pnpm generate:dts-exports`
import type {
  _createNode,
  decodeJsonParams,
  encodeJsonParams,
  RouterProvider,
  useIntentLink,
  useLink,
  useRouter,
  useRouterState,
  useStateLink,
  withRouter,
  BaseIntentParams,
  IntentJsonParams,
  IntentLink,
  IntentLinkProps,
  IntentParameters,
  InternalSearchParam,
  Link,
  LinkProps,
  MatchError,
  MatchOk,
  MatchResult,
  NavigateBaseOptions,
  NavigateOptions,
  NavigateOptionsWithState,
  NextStateOrOptions,
  Route,
  route,
  RouteChildren,
  RouteNodeOptions,
  RouteObject,
  Router,
  RouterContext,
  RouterContextValue,
  RouterNode,
  RouterProviderProps,
  RouterState,
  RouteScope,
  RouteScopeProps,
  RouteSegment,
  RouteTransform,
  SearchParam,
  StateLink,
  StateLinkProps,
  STICKY_PARAMS,
  UseIntentLinkOptions,
  UseLinkOptions,
  UseStateLinkOptions,
  WithRouter,
  WithRouterProps,
} from 'sanity/router'
import {describe, expectTypeOf, test} from 'vitest'

describe('sanity/router', () => {
  test('_createNode', () => {
    expectTypeOf<typeof _createNode>().toBeFunction()
  })
  test('decodeJsonParams', () => {
    expectTypeOf<typeof decodeJsonParams>().toBeFunction()
  })
  test('encodeJsonParams', () => {
    expectTypeOf<typeof encodeJsonParams>().toBeFunction()
  })
  test('RouterProvider', () => {
    expectTypeOf<typeof RouterProvider>().toBeFunction()
  })
  test('useIntentLink', () => {
    expectTypeOf<typeof useIntentLink>().toBeFunction()
  })
  test('useLink', () => {
    expectTypeOf<typeof useLink>().toBeFunction()
  })
  test('useRouter', () => {
    expectTypeOf<typeof useRouter>().toBeFunction()
  })
  test('useRouterState', () => {
    expectTypeOf<typeof useRouterState>().toBeFunction()
  })
  test('useRouterState', () => {
    expectTypeOf<typeof useRouterState>().toBeFunction()
  })
  test('useStateLink', () => {
    expectTypeOf<typeof useStateLink>().toBeFunction()
  })
  test('withRouter', () => {
    expectTypeOf<typeof withRouter>().toBeFunction()
  })
  test('BaseIntentParams', () => {
    expectTypeOf<BaseIntentParams>().toBeObject()
  })
  test('IntentJsonParams', () => {
    expectTypeOf<IntentJsonParams>().not.toBeNever()
  })
  test('IntentLink', () => {
    expectTypeOf<typeof IntentLink>().not.toBeNever()
  })
  test('IntentLinkProps', () => {
    expectTypeOf<IntentLinkProps>().toBeObject()
  })
  test('IntentParameters', () => {
    expectTypeOf<IntentParameters>().not.toBeNever()
  })
  test('InternalSearchParam', () => {
    expectTypeOf<InternalSearchParam>().not.toBeNever()
  })
  test('Link', () => {
    expectTypeOf<typeof Link>().not.toBeNever()
  })
  test('LinkProps', () => {
    expectTypeOf<LinkProps>().toBeObject()
  })
  test('MatchError', () => {
    expectTypeOf<MatchError>().toBeObject()
  })
  test('MatchOk', () => {
    expectTypeOf<MatchOk>().toBeObject()
  })
  test('MatchResult', () => {
    expectTypeOf<MatchResult>().not.toBeNever()
  })
  test('NavigateBaseOptions', () => {
    expectTypeOf<NavigateBaseOptions>().toBeObject()
  })
  test('NavigateOptions', () => {
    expectTypeOf<NavigateOptions>().toBeObject()
  })
  test('NavigateOptionsWithState', () => {
    expectTypeOf<NavigateOptionsWithState>().toBeObject()
  })
  test('NextStateOrOptions', () => {
    expectTypeOf<NextStateOrOptions>().not.toBeNever()
  })
  test('Route', () => {
    expectTypeOf<Route>().toBeObject()
  })
  test('route', () => {
    expectTypeOf<typeof route>().not.toBeNever()
  })
  test('RouteChildren', () => {
    expectTypeOf<RouteChildren>().not.toBeNever()
  })
  test('RouteNodeOptions', () => {
    expectTypeOf<RouteNodeOptions>().toBeObject()
  })
  test('RouteObject', () => {
    expectTypeOf<RouteObject>().toBeObject()
  })
  test('Router', () => {
    expectTypeOf<Router>().toBeObject()
  })
  test('RouterContext', () => {
    expectTypeOf<typeof RouterContext>().not.toBeNever()
  })
  test('RouterContextValue', () => {
    expectTypeOf<RouterContextValue>().toBeObject()
  })
  test('RouterNode', () => {
    expectTypeOf<RouterNode>().toBeObject()
  })
  test('RouterProviderProps', () => {
    expectTypeOf<RouterProviderProps>().toBeObject()
  })
  test('RouterState', () => {
    expectTypeOf<RouterState>().not.toBeNever()
  })
  test('RouteScope', () => {
    expectTypeOf<typeof RouteScope>().not.toBeNever()
  })
  test('RouteScopeProps', () => {
    expectTypeOf<RouteScopeProps>().toBeObject()
  })
  test('RouteSegment', () => {
    expectTypeOf<RouteSegment>().toBeObject()
  })
  test('RouteTransform', () => {
    expectTypeOf<RouteTransform<any>>().toBeObject()
  })
  test('SearchParam', () => {
    expectTypeOf<SearchParam>().not.toBeNever()
  })
  test('StateLink', () => {
    expectTypeOf<typeof StateLink>().not.toBeNever()
  })
  test('StateLinkProps', () => {
    expectTypeOf<StateLinkProps>().toBeObject()
  })
  test('STICKY_PARAMS', () => {
    expectTypeOf<typeof STICKY_PARAMS>().not.toBeNever()
  })
  test('UseIntentLinkOptions', () => {
    expectTypeOf<UseIntentLinkOptions>().toBeObject()
  })
  test('UseLinkOptions', () => {
    expectTypeOf<UseLinkOptions>().toBeObject()
  })
  test('UseStateLinkOptions', () => {
    expectTypeOf<UseStateLinkOptions>().toBeObject()
  })
  test('WithRouter', () => {
    expectTypeOf<typeof WithRouter>().not.toBeNever()
  })
  test('WithRouterProps', () => {
    expectTypeOf<WithRouterProps>().toBeObject()
  })
})
