// Auto-generated by running `pnpm generate:dts-exports`
import type {cliProjectCommands} from 'sanity/_internal'
import {describe, expectTypeOf, test} from 'vitest'

describe('sanity/_internal', () => {
  test('cliProjectCommands', () => {
    expectTypeOf<typeof cliProjectCommands>().not.toBeNever()
  })
})
