// Auto-generated by running `pnpm generate:dts-exports`
import type {
  getStudioEnvironmentVariables,
  CliClientOptions,
  CliConfig,
  createCliConfig,
  defineCliConfig,
  getCliClient,
  StudioEnvVariablesOptions,
} from 'sanity/cli'
import {describe, expectTypeOf, test} from 'vitest'

describe('sanity/cli', () => {
  test('getStudioEnvironmentVariables', () => {
    expectTypeOf<typeof getStudioEnvironmentVariables>().toBeFunction()
  })
  test('CliClientOptions', () => {
    expectTypeOf<CliClientOptions>().toBeObject()
  })
  test('CliConfig', () => {
    expectTypeOf<CliConfig>().toBeObject()
  })
  test('createCliConfig', () => {
    expectTypeOf<typeof createCliConfig>().toBeFunction()
  })
  test('defineCliConfig', () => {
    expectTypeOf<typeof defineCliConfig>().toBeFunction()
  })
  test('getCliClient', () => {
    expectTypeOf<typeof getCliClient>().toBeFunction()
  })
  test('getCliClient', () => {
    expectTypeOf<typeof getCliClient>().not.toBeNever()
  })
  test('StudioEnvVariablesOptions', () => {
    expectTypeOf<StudioEnvVariablesOptions>().toBeObject()
  })
})
