// Auto-generated by running `pnpm generate:dts-exports`
import type {createContext} from 'sanity/_createContext'
import {describe, expectTypeOf, test} from 'vitest'

describe('sanity/_createContext', () => {
  test('createContext', () => {
    expectTypeOf<typeof createContext>().toBeFunction()
  })
})
