name: Test exports works in native node ESM and CJS and TypeScript DTS
on:
  push:
    paths-ignore:
      - "examples/**"
jobs:
  testExports:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*

      - name: Install project dependencies
        run: pnpm install

      - name: Check export conditions in native node ESM and CJS, and TypeScript DTS
        run: pnpm test:exports
